columnSuffix: null
contentColumnType: string
fieldGroup: 5dcc4492-44cb-41c4-ae05-b3ddf1a3a30e # homepage
handle: heroImage
instructions: ''
name: 'Hero Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:615d6b30-3f80-4bbb-9001-2b6a837b5799' # Uploads
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add a background image'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:615d6b30-3f80-4bbb-9001-2b6a837b5799' # Uploads
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:615d6b30-3f80-4bbb-9001-2b6a837b5799' # Uploads
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
