columnSuffix: null
contentColumnType: string
fieldGroup: 5dcc4492-44cb-41c4-ae05-b3ddf1a3a30e # homepage
handle: riders
instructions: ''
name: Riders
searchable: false
settings:
  contentTable: '{{%matrixcontent_riders}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
