defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  aa49cf5b-be62-4d34-96e9-52b77d71e617: # animeblog
    enabledByDefault: true
    hasUrls: true
    template: home
    uriFormat: __home__
type: single
